/* PostgreSQL 13+ 用の同期補助テーブルと差し替え可能なサンプル Entity。 */
CREATE TABLE public."SyncChangeQueue"
(
    "QueueId" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "MessageId" uuid NOT NULL,
    "EntityType" varchar(128) NOT NULL,
    "EntityId" varchar(256) NOT NULL,
    "Operation" varchar(16) NOT NULL,
    "OccurredAtUtc" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public."SyncAppliedMessage"
(
    "MessageId" uuid PRIMARY KEY,
    "AppliedAtUtc" timestamptz NOT NULL
);

CREATE TABLE public."SyncEntityOrigin"
(
    "EntityType" varchar(128) NOT NULL,
    "EntityId" varchar(256) NOT NULL,
    "OriginSystem" varchar(64) NOT NULL,
    PRIMARY KEY ("EntityType", "EntityId")
);

CREATE TABLE public."SyncDeleteTombstone"
(
    "MessageId" uuid NOT NULL,
    "EntityType" varchar(128) NOT NULL,
    "EntityId" varchar(256) NOT NULL,
    "OriginSystem" varchar(64) NOT NULL,
    "PayloadJson" jsonb NOT NULL,
    "DeletedAtUtc" timestamptz NOT NULL,
    PRIMARY KEY ("MessageId", "EntityType", "EntityId")
);

CREATE TABLE public."SyncCoordinatorDeployment"
(
    "DeploymentKey" varchar(128) PRIMARY KEY,
    "DefinitionHash" char(64) NOT NULL,
    "AppliedAtUtc" timestamptz NOT NULL
);

CREATE TABLE public."SampleSyncEntity"
(
    "EntityType" varchar(128) NOT NULL,
    "EntityId" varchar(256) NOT NULL,
    "OriginSystem" varchar(64) NOT NULL,
    "PayloadJson" jsonb NOT NULL,
    "IsDeleted" boolean NOT NULL DEFAULT false,
    "UpdatedAtUtc" timestamptz NOT NULL,
    PRIMARY KEY ("EntityType", "EntityId")
);

/* 実際のTriggerは管理画面のテーブル／列マッピングから生成する。 */
